/*
 * futureImageProvider.js — provider seam for the AI "future scene" image (founder §4 / RC-17 P3).
 *
 * The provider is OPENAI (founder: IMAGE_PROVIDER = OPENAI, default model gpt-image-2.5-flare), called
 * SERVER-SIDE by the generate-future-image edge function so the OPENAI_API_KEY never reaches the
 * client, the server builds the final prompt, and the server usage table is the billing authority.
 *
 * HONESTY: generate() returns { state:'not_configured' } and NEVER a fabricated image when the backend
 * seam is not configured. When configured, it delegates to the edge function; a real ready image comes
 * back as { state:'ready', imageUrl }, and provider/quota failures come back as { state:'failed' } —
 * never a placeholder. The caller (useImageUsage) still checks the local ledger BEFORE calling as a UX
 * pre-check, but the SERVER quota is authoritative and only a real success is charged there.
 */
import { IMAGE_PREVIEW_QUALITY, IMAGE_FINAL_QUALITY } from '../constants/imagePolicy.js';
import { isSupabaseConfigured, generateFutureImageRemote } from './supabaseClient.js';

// The image is generated by the server edge function, which requires the Supabase backend to be
// configured (to invoke it) AND the OPENAI_API_KEY set as a server secret. The client can only probe
// the backend seam; the server reports its own not-configured state honestly if the key is missing.
export function isImageProviderConfigured() {
  return isSupabaseConfigured();
}

// Package the request the CLIENT sends to the server. Pure — makes no call. The server builds the
// FINAL prompt from this; the client never crafts the provider prompt itself.
export function buildImageRequest({ diaryText = '', quality = IMAGE_PREVIEW_QUALITY } = {}) {
  return {
    diaryText: String(diaryText).trim().slice(0, 1000),
    quality: quality === IMAGE_FINAL_QUALITY ? IMAGE_FINAL_QUALITY : IMAGE_PREVIEW_QUALITY,
  };
}

/**
 * generate — returns a state object, never a fake image.
 * @returns {Promise<{state:'not_configured'|'generating'|'ready'|'failed', imageUrl?:string, error?:string, used?:number, limit?:number}>}
 */
export async function generate(opts = {}) {
  if (!isImageProviderConfigured()) return { state: 'not_configured' };
  const req = buildImageRequest(opts);
  // Map the product quality tokens (LOW/MEDIUM) to the server's low/medium; default preview = low.
  const quality = req.quality === IMAGE_FINAL_QUALITY ? 'medium' : 'low';
  return generateFutureImageRemote({ diaryText: req.diaryText, quality });
}

// ── runnable self-check ──
if (typeof process !== 'undefined' && Array.isArray(process.argv) && import.meta.url === `file://${process.argv[1]}`) {
  const assert = (c, m) => {
    if (!c) throw new Error(m);
  };
  assert(isImageProviderConfigured() === false, 'no provider configured by default (no backend)');
  const req = buildImageRequest({ diaryText: '건강한 하루', quality: 'MEDIUM' });
  assert(req.quality === 'MEDIUM' && req.diaryText === '건강한 하루', 'request built from prose + quality');
  assert(buildImageRequest({ quality: 'weird' }).quality === IMAGE_PREVIEW_QUALITY, 'unknown quality → preview');
  generate({ diaryText: 'x' }).then((r) => {
    assert(r.state === 'not_configured' && !r.imageUrl, 'generate returns not_configured, no fake image');
    console.log('futureImageProvider.js self-check OK');
  });
}
