// GENERATED by scripts/build-blocklist.mjs — do not edit by hand.
// The service worker imports this so GET_STATUS reports the REAL bundled list version/type/count.
export const BLOCKLIST_META = {
  "version": 1,
  "listType": "fixture",
  "domainCount": 7,
  "ruleCount": 1,
  "updatedAt": "2026-09-21",
  "compiledSha256": "bc8c2ba49a894e8076e0b4e03ee4c77d747b3be3c829111f3bff13faf922d7f3"
};
